system:
  debug: 
    log_level: debug

ai:
  provider: "openai" # "openai" or "vertexai"
  openai:
    model: "gpt-4o-mini" # Check the list of available models by `curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"`

  vertexai:
    project: "<YOUR_PROJECT_ID>"
    location: "us-central1"
    model: "gemini-2.0-flash-001"
  
  commands:
    - describe:
        description: "Generate a detailed description of the Issue."
        system_prompt: "The following is the GitHub Issue and comments on it. Please Generate a detailed description.\n"
        similar_code: false
        similar_issue: true
        require_intent: false
    - suggest:
        description: "Provide suggestions for improvement based on the contents of the Issue."
        system_prompt: "The following is the GitHub Issue and comments on it. Please identify the issues that need to be resolved based on the contents of the Issue and provide three suggestions for improvement.\n"
        similar_code: true
        similar_issue: false
        require_intent: false
    - ask:
        description: "Answer free-text questions."
        system_prompt: "The following is the GitHub Issue and comments on it. Based on the content provide a detailed response to the following question:\n"
        similar_code: true
        similar_issue: false
        require_intent: true
    - analysis:
        description: "Perform a structured analysis of the Issue to help with resolution."
        system_prompt: |
          以下はGitHub Issueとそれに対するコメントです。以下の手順に従って、問題の包括的な分析を行ってください：
          1) 主要な症状と観察された動作を特定する
          2) 症状に基づいて、潜在的な根本原因を特定する。
          3) それぞれの潜在的な原因を評価し、その可能性を判断する。
          4) 各仮説を確認または否定するデータポイントのリストアップ
          5) 問題解決のための体系的なアプローチを提案する。
          6) 提案された解決策の潜在的なリスクや副作用を特定する
        similar_code: true
        similar_issue: false
        require_intent: false
